repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: flake8
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
  # - repo: https://github.com/pre-commit/mirrors-isort
  #   rev: "master"
  #   hooks:
  #       - id: isort
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: "master"
    hooks:
      - id: pylint
        args:
          - --disable=C0103,C0302,C0330,E0401,R0205,R0801,R0902,R0903,R0904,R0912,R0913,R0914,R0915,R1702,W0212,W0511,W0703,W1202
